export const spaceDetailDummyData = {
  id: 1,
  name: '이름',
  description: '이름',
  imageUrls: [
    'https://picsum.photos/250/250',
    'https://picsum.photos/250/250',
    'https://picsum.photos/250/250',
  ],
  category: '이름',
  openingTime: '이름',
  closingTime: '이름',
  capacity: 100,
  tags: ['20대 여성이 가장 많아요', '데이트 장소 핫플', '주말에 사람이 가장 많아요'],
  pricePerDay: 1,
  discountRate: 1,
  details:
    '이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름이름',
  latitude: 37.5665,
  longitude: 126.978,
  city: '이름',
  district: '이름',
  address: '이름',
  detailAddress: '이름',
  websiteUrl: '이름',
  contactNumber: '이름',
  facilityInfo: '이름',
  notice: '이름',
  likeCount: 1,
  isLiked: true,
  messageRoomId: 1,
};
